import './globals.css';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import Navbar from './components/Navbar/Navbar';
import ContactoPage from './contacto/page';
import NuestrosTrabajosPage from './nuestros-trabajos/page';

const ubuntu = Roboto({
	subsets: ['latin'],
	variable: '--font-Roboto',
	weight: ['500'],
	preload: true,
});

export const metadata: Metadata = {
	title: 'LBI Construcciones',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='es'>
			<body className={ubuntu.className + ' flex flex-col h-screen w-full'}>
				<Navbar />
				<main className='flex flex-col w-full h-max gap-2 text-white'>{children}</main>
			</body>
		</html>
	);
}
